### PR TITLE
Bugfix - Fixed hiding with acceptance & difficulty

### PR DESCRIPTION
**Pull request by nickzuber**
I noticed recently that this extension stopped working for me - I'm assuming that the site was updated or something.

This PR now hides the acceptance and difficulty columns on the main page, as well as the question stats while you're inside the context of solving a problem.

### CODE REVIEW

**Comment by anna-yn** [comment]
Just uploaded new version to chrome store, should be visible in a bit. Thanks!!

**Comment by nickzuber** [comment]
@Nevvea7 Note that this will hide the information upon page load, and we're going to need to rehide everything when the page updates (pagination etc). Also the content loads dynamically so sometimes we need to wait for some time _after_ the page is loaded to start hiding.

We can solve this by listening to the DOM and rehiding the contents whenever anything changes (it looks like you attempt to do this already with the jquery-watch plugin, I'm not familiar with this so idk lol) but I think that might need to be updated as well

**Comment by anna-yn** [comment]
@nickzuber :/ frontend and js really aren't my thing...but im guessing the things we're trying to hide isn't gonna change once the page finish loading?
Also for some reason that jquery-watch plugin gets triggered 3-4 times once the page loads -- looks like that part of the page just reloads itself multiple times with invisible "Pending", "Judging", "Accepted" etc and that's why I have the hacky count there to check whether it's really showing "Accepted" or not

**Comment by nickzuber** [comment]
@Nevvea7 So the "gotchya" here is whenever you go onto the next page of questions, the DOM will update to display the new set of questions (you aren't actually taken to a new page, so to speak). 

Another "gotchya" is that the questions are loaded dynamically, which means they only render onto the page once they've been loaded, which, depending on the user's internet connection, could be anywhere from like a half a second to 5 seconds after the page has initially loaded.

So the trick here is we want to try and hide those fields whenever this content on the DOM updates. One way we can solve this is to have our `hide` function that hides all the fields we want, and then write a small program that listens to the DOM for any changes, and whenever we detect a change, we want to execute that `hide` function.

I'm not too familiar with that juqery plugin, but I know there's a native (and well supported :smile: ) way to do this in javascript using a [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver)

**Pull request merged**
